---
version: "3.7"
services:
  mycart-frontend:
    build:
      context: ./frontend
    image: konavara/mycart-frontend:4.0
    depends_on: 
      - mycart-backend
    environment:
      BACKENDLB: mycart-backend
    ports:
      - "9000:80"
    volumes:
      - type: volume
        source: mycart-frontend-logvol
        target: /var/log
  mycart-db:
    image: mysql:5.7
    volumes:
      - type: volume
        source: mycart-db-vol
        target: /var/lib/mysql
  mycart-backend:
    build:
      context: ./backend
    image: konavara/mycart-backend:4.0
    volumes:
      - type: volume
        source: mycart-backend-logvol
        target: /var/log
volumes:
  mycart-frontend-logvol:
  mycart-backend-logvol:
  mycart-db-vol: